# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Advertising_header', models.CharField(max_length=200)),
                ('Advertising_text', models.TextField()),
                ('Advertising_date', models.DateTimeField()),
                ('Advertising_price', models.CharField(default=0, max_length=10)),
            ],
            options={
                'db_table': 'Advertising',
            },
        ),
    ]
