# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 11:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='Advertising_image',
            field=models.CharField(default=datetime.datetime(2016, 1, 3, 11, 40, 3, 705750, tzinfo=utc), max_length=255, verbose_name='Ссылка на картинку'),
            preserve_default=False,
        ),
    ]
