# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0002_advertising_advertising_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='uid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='Advertising_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='Advertising_header',
            field=models.CharField(max_length=200, verbose_name='Кратное описание'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='Advertising_price',
            field=models.CharField(default=0, max_length=10, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='Advertising_text',
            field=models.TextField(verbose_name='Описание объявления'),
        ),
    ]
