# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0004_auto_20160103_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='Advertising_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='Advertising_header',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='Advertising_price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='Advertising_text',
            field=models.TextField(),
        ),
    ]
