# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0007_remove_advertising_advertising_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='Advertising_price',
            field=models.IntegerField(default=0, max_length=10, verbose_name='Стоимость'),
        ),
    ]
