# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 12:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0008_auto_20160105_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='Advertising_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 7, 12, 9, 44, 846979, tzinfo=utc), verbose_name='Дата публикации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertising',
            name='Advertising_price',
            field=models.IntegerField(default=0, verbose_name='Стоимость'),
        ),
    ]
