# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0009_auto_20160107_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField(verbose_name='Введите комментарий')),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
        migrations.AlterField(
            model_name='advertising',
            name='Advertising_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comments_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adds.Advertising'),
        ),
    ]
