# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 10:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0011_auto_20160108_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comments_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 8, 10, 52, 1, 461387, tzinfo=utc), verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
