# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0013_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='pic',
        ),
        migrations.AddField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
