# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0014_auto_20160110_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='adds/images'),
        ),
    ]
