# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0015_auto_20160110_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='img_advertising',
        ),
        migrations.AddField(
            model_name='advertising',
            name='Advertising_picture',
            field=models.ImageField(blank=True, null=True, upload_to='adds/images'),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
