# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0022_auto_20160110_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertising',
            name='Advertising_picture_name',
        ),
    ]
