# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0026_auto_20160110_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='Advertising_picture',
            field=models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='', verbose_name='D:\\Project\\commechal\\media\\static'),
        ),
    ]
